-   id: rome
    name: rome
    description: 'Format using rome'
    entry: rome format --write
    language: node
    files: \.[js,jsx,ts,tsx]$
    args: []
    require_serial: false
    additional_dependencies: ["rome@12.1.3"]
    minimum_pre_commit_version: '0'
